AllCops:
  Exclude:
    - Gemfile
    - bin/*
    - config/boot.rb
    - rgloader/loader.rb
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
Encoding:
  Enabled: false
LineLength:
  Max: 180
MethodLength:
  Max: 90
Documentation:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Style/ClassAndModuleChildren:
  SupportedStyles: compact
Style/RaiseArgs:
  Enabled: false
SignalException:
  Enabled: false
ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 150
EachWithObject:
  Enabled: false
PerceivedComplexity:
  Enabled: false
TrivialAccessors:
  Enabled: false
Lint/RescueException:
  Enabled: false
RedundantSelf:
  Enabled: false
Style/Lambda:
  Enabled: false
AbcSize:
  Enabled: false
BlockDelimiters:
  Enabled: true
MultilineOperationIndentation:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
